version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01:/usr/share/elasticsearch/data
      - ./elk/config/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kib01
    volumes:
      - ./elk/config/kib01.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - es01
    networks:
      - elastic

volumes:
  es01:
    driver: local

networks:
  elastic:
    driver: bridge
